export const FETCH_ALL_GROUPS = 'FETCH_ALL_GROUPS';
export const LOADING_GROUPS_ERROR = 'LOADING_GROUPS_ERROR';


export const ADD_GROUP = "ADD_GROUP";
export const ADD_PICTURE = "ADD_PICTURE";

export const LOAD_GROUP = "LOAD_GROUP";
export const LOAD_GROUP_ERRORS = "LOAD_GROUP_ERRORS";