export const curiosities = [
    {id: 0, content: "Najwięcej browarów w jednym mieście działa w niemieckim Bambergu, gdzie zlokalizowanych jest aż dziesięć zakładów produkujących chmielowy trunek."},
    {id: 1, content: "Litr piwa można wypić w 1,3 sekundy! Tyle potrzebował niejaki Steven Petrosino w 1997. Ustanowił tym samym rekord, którego nie pobito do dziś. Nie zachęcamy do prób pokonania pana Petrosino. Piwem należy się przecież delektować!"},
    {id: 2, content: "123,7 metra liczy najdłuższa lada barowa na świecie. Znajduje się w barze Beer Barrel Salloon na północnoamerykańskie wyspie South Bass Island (jezioro Erie). Jest na niej zamocowanych 56 nalewaków."},
    {id: 3, content: "Praga może pochwalić się najstarszą piwiarnią z własnym browarem. Piwo w „U Fleku” zaczęto bowiem warzyć już XV wieku. Najstarsze zapiski na ten temat datowane są na 1499 roku."},
    {id: 4, content: "Awaria w londyńskim browarze Meux and Company w 1834 roku spowodowała, że ulicami stolicy Wielkiej Brytanii spłynęło 1,5 mln litrów portera. Piwna powódź kosztowała życie 8 osób."},
    {id: 5, content: "Kadź z porterem, której pęknięcie wywołało powódź piwa w Londynie była swego czasu największa na świecie i mieściła 860 tys. galonów (ponad 3,8 mln litrów) portera. Zbudowano ją w 1795 roku."},
    {id: 6, content: "Do 2013 roku w Rosji piwo (i inne napoje o zawartości alkoholu poniżej 10 proc.) nie było uważane za alkohol, więc można je było kupić bez żadnych ograniczeń."},
    {id: 7, content: "Najstarszy browar, który działa po dziś dzień powstał w 1040 roku. Mieści się w miasteczku Freising w Bawarii. Piwo warzone jest w benedyktyńskim klasztorze Weihenstephan. Znajduje się tam także najsłynniejsza na świecie szkoła piwowarów."},
    {id: 8, content: "Kodeks Hammurabiego przewidywał karę śmierci przez utopienie dla piwowara przyłapanego na dodawaniu wody do piwa."},
    {id: 9, content: "Pierwsze piwo w puszcze wyprodukowano w 1935 roku w Ameryce. Puszka ważyła aż 100 gram, była więc cztery razy cięższa niż obecnie. Przy okazji obalamy piwny mit: piwo w puszkach nie smakuje gorzej od butelkowanego. Obecnie stosowana technologia chroni przed wchodzeniem trunku w reakcję z metalem, co mogłoby psuć walory smakowe chmielowego napitku."}
]