export const FETCH_ALL_BREWERIES = 'FETCH_ALL_BREWERIES';
export const LOADING_BREWERIES_ERRORS = 'LOADING_BREWERIES_ERRORS';


export const LOAD_BREWERY = "LOAD_BREWERY";
export const LOADING_BREWERY_ERRORS = "LOADING_BREWERY_ERRORS";


export const ADD_BREWERY = "ADD_BREWERY";
