export const LOGING_IN = 'LOGING_IN';
export const REGISTER = 'REGISTER';
export const CHANGE_REGISTER_STATUS = 'CHANGE_REGISTER_STATUS';
export const SET_USER_ADMIN = "SET_USER_ADMIN";
export const CHANGE_LOGIN_STATUS = "CHANGE_LOGIN_STATUS";


